#+TITLE:Emacs-Config
#+PROPERTY: header-args :tangle config.el

* Table of Contents  :toc:
- [[#user-information][User Information]]
- [[#appearance][Appearance]]
  - [[#theme][Theme]]
  - [[#line-numbers][Line Numbers]]
  - [[#start-up-setting][Start up setting]]
  - [[#font-settings][Font Settings]]
  - [[#emoji-settings][Emoji Settings]]
- [[#org-mode][Org Mode]]
  - [[#general-org-mode][General org mode]]
  - [[#directories][Directories]]
  - [[#tood-lists-and-bullets][TOOD lists and bullets]]
- [[#additional-documentation][Additional documentation]]

* User Information
My name and email address. Currently, I don't have an email client for emacs set up but this would be useful then
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Calvin Roth"
      user-mail-address "rothx195@umn.edu")
#+END_SRC

#+RESULTS:
: rothx195@umn.edu

Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:
 - `doom-font'
 - `doom-variable-pitch-font'
 - `doom-big-font' -- used for `doom-big-font-mode'; use this for
    presentations or streaming

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
       doom-variable-pitch-font (font-spec :family "sans" :size 13))

* Appearance

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. To preview other themes press SPACE+h+t.
** Theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src

#+RESULTS:
: doom-one

** Line Numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers(meaning distance from current line), set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type `relative)
#+end_src

#+RESULTS:
: relative

** Start up setting
Start emacs in full screen
#+begin_src emacs-lisp
(add-hook 'window-setup-hook 'toggle-frame-fullscreen t)
#+end_src

#+RESULTS:
| doom-modeline-refresh-font-width-cache | doom-init-menu-bar-in-gui-frames-h | doom-display-benchmark-h | doom-init-tty-h | doom-init-ui-h | toggle-frame-fullscreen |

** Font Settings
Next make the font size bigger. Also change font here
#+begin_src emacs-lisp
(set-face-attribute 'default nil :height 200)
#+end_src

#+RESULTS:

** Emoji Settings
Finally, we set the style of emoji we want to use. Here we use the twitter style
#+begin_src emacs-lisp
(setq emojify-emoji-set "twemoji-v2")
#+end_src

#+RESULTS:
: twemoji-v2

* Org Mode

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

** General org mode
First, we turn on toggle pretty entities this turns simple math into the appropriate symbol. For example, epsilon becomes \epsilon and
to becomes \to . In general, use latex rules, in particular math commands start with a slash \ normally. Super/subscripts work now too.
#+begin_src emacs-lisp
(after! org
  (setq org-pretty-entities t)
)
#+end_src

#+RESULTS:
: t

We will also hide emphasis markers. In org mode / + text + / with no spaces for the slashes yields italtic text: /text/ and likewise for *Bold Text* using the * symbol. This command hides the slashes and stars.
#+begin_src emacs-lisp
(after! org
  (setq org-hide-emphasis-markers t)
)
#+end_src

#+RESULTS:
: t

** Directories
#+begin_src emacs-lisp
(after! org
  (setq org-directory "~/org/")
  (setq org-agenda-files "/org/weekly.org")
)
#+end_src

#+RESULTS:
: /org/weekly.org

** TOOD lists and bullets
This makes it so when all the children of a TOOD item are DONE then the parent is automatically marked as done
#+begin_src emacs-lisp
(defun org-summary-todo (n-done n-not-done)
  "Switch entry to DONE when all subentries are done, to TODO otherwise."
  (let (org-log-done org-log-states)   ; turn off logging
    (org-todo (if (= n-not-done 0) "DONE✅" "TODO🌊"))))
    ;; I included the statistics here.
(add-hook 'org-after-todo-statistics-hook 'org-summary-todo)
#+end_src

#+RESULTS:
| org-summary-todo |

This package is for prettier bullets
#+begin_src emacs-lisp
(after! org
  (use-package! org-bullets
      :config
      (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
)
#+end_src

#+RESULTS:
: t


Just as the org bullet packages redefine the bullets for headings, I define the - symbol when used in a list to be an emoji.
#+begin_src emacs-lisp
(after! org)
(font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "🔹"))))))
#+end_src

#+RESULTS:

* Additional documentation
Here are some additional functions/macros that could help you configure Doom:

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
   this file. Emacs searches the `load-path' when you load packages with
   `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.
